/*
  Unit tests for the REST API handler for the /users endpoints.
*/

// Public npm libraries
// const assert = require('chai').assert
// const sinon = require('sinon')
import { assert } from 'chai'
import sinon from 'sinon'

// Local support libraries
import adapters from '../../../mocks/adapters/index.js'
import UseCasesMock from '../../../mocks/use-cases/index.js'

import SlpController from '../../../../../src/controllers/rest-api/slp/controller.js'

import { context } from '../../../../unit/mocks/ctx-mock.js'
let uut
let sandbox
let ctx
const mockContext = context

describe('#Slp-REST-Controller', () => {
  // const testUser = {}

  beforeEach(() => {
    const useCases = new UseCasesMock()
    uut = new SlpController({ adapters, useCases })

    sandbox = sinon.createSandbox()

    // Mock the context object.
    ctx = mockContext()
  })

  afterEach(() => sandbox.restore())

  describe('#constructor', () => {
    it('should throw an error if adapters are not passed in', () => {
      try {
        uut = new SlpController()

        assert.fail('Unexpected code path')
      } catch (err) {
        assert.include(
          err.message,
          'Instance of Adapters library required when instantiating /slp REST Controller.'
        )
      }
    })

    it('should throw an error if useCases are not passed in', () => {
      try {
        uut = new SlpController({ adapters })

        assert.fail('Unexpected code path')
      } catch (err) {
        assert.include(
          err.message,
          'Instance of Use Cases library required when instantiating /slp REST Controller.'
        )
      }
    })
  })

  describe('#POST /address', () => {
    it('should return 422 status on biz logic error', async () => {
      try {
        await uut.address(ctx)

        assert.fail('Unexpected result')
      } catch (err) {
        // console.log(err)
        assert.equal(err.status, 422)
        assert.include(err.message, 'Cannot read')
      }
    })

    it('should return 200 status on success', async () => {
      // Mock dependencies
      sandbox.stub(uut.adapters.slpIndexer.query, 'getAddress').resolves({ key: 'value' })

      ctx.request.body = {
        address: 'fake-address'
      }

      await uut.address(ctx)

      // Assert the expected HTTP response
      assert.equal(ctx.status, 200)

      // Assert that expected properties exist in the returned data.
      assert.property(ctx.response.body, 'balance')
    })
  })

  describe('#POST /tx', () => {
    it('should return 422 status on biz logic error', async () => {
      try {
        await uut.tx(ctx)

        assert.fail('Unexpected result')
      } catch (err) {
        // console.log(err)
        assert.equal(err.status, 422)
        assert.include(err.message, 'Cannot read')
      }
    })

    it('should return 200 status on success', async () => {
      // Mock dependencies
      sandbox.stub(uut.adapters.slpIndexer.query, 'getTx').resolves({ key: 'value' })

      ctx.request.body = {
        txData: 'fake-address'
      }

      await uut.tx(ctx)

      // Assert the expected HTTP response
      assert.equal(ctx.status, 200)

      // Assert that expected properties exist in the returned data.
      assert.property(ctx.response.body, 'txData')
    })
  })

  describe('#POST /token', () => {
    it('should return 422 status on biz logic error', async () => {
      try {
        await uut.token(ctx)

        assert.fail('Unexpected result')
      } catch (err) {
        // console.log(err)
        assert.equal(err.status, 422)
        assert.include(err.message, 'Cannot read')
      }
    })

    it('should return 200 status on success', async () => {
      // Mock dependencies
      sandbox.stub(uut.adapters.slpIndexer.query, 'getToken').resolves({ key: 'value' })

      ctx.request.body = {
        tokenData: 'fake-address'
      }

      await uut.token(ctx)

      // Assert the expected HTTP response
      assert.equal(ctx.status, 200)

      // Assert that expected properties exist in the returned data.
      assert.property(ctx.response.body, 'tokenData')
    })
  })

  describe('#handleError', () => {
    it('should still throw error if there is no message', () => {
      try {
        const err = {
          status: 404
        }

        uut.handleError(ctx, err)
      } catch (err) {
        assert.include(err.message, 'Not Found')
      }
    })

    it('should still throw error if there is a message', () => {
      try {
        const err = {
          status: 404,
          message: 'test error'
        }

        uut.handleError(ctx, err)
      } catch (err) {
        assert.include(err.message, 'test error')
      }
    })
  })
})
